module Tag where

data Tag = CC | CD | DT | EX | FW | IN | JJ | JJR   | JJS   | LS  | MD  | NN  | NNS | NNP | NNPS | PDT | POS | PRP | PRPs | RB  | RBR | RBS | RP  | SYM | TO  | UH  | VB  | VBD | VBG | VBN | VBP | VBZ | WDT | WP  | WPs | WRB | P
  deriving (Read, Eq, Ord)

instance Show Tag where
  show CC   = "{CC} Coordinating conjunction"
  show CD   = "{CD} Cardinal number"
  show DT   = "{DT} Determiner"
  show EX   = "{EX} Existential there"
  show FW   = "{FW} Foreign word"
  show IN   = "{IN} Preposition or subordinating conjunction"
  show JJ   = "{JJ} Adjective"
  show JJR  = "{JJR} Adjective, comparative"
  show JJS  = "{JJS} Adjective, superlative"
  show LS   = "{LS} List item marker"
  show MD   = "{MD} Modal"
  show NN   = "{NN} Noun, singular or mass"
  show NNS  = "{NNS} Noun, plural"
  show NNP  = "{NNP} Proper noun, singular"
  show NNPS = "{NNPS} Proper noun, plural"
  show PDT  = "{PDT} Predeterminer"
  show POS  = "{POS} Possessive ending"
  show PRP  = "{PRP} Personal pronoun"
  show PRPs = "{PRP$} Possessive pronoun"
  show RB   = "{RB} Adverb"
  show RBR  = "{RBR} Adverb, comparative"
  show RBS  = "{RBS} Adverb, superlative"
  show RP   = "{RP} Particle"
  show SYM  = "{SYM} Symbol"
  show TO   = "{TO} to"
  show UH   = "{UH} Interjection"
  show VB   = "{VB} Verb, base form"
  show VBD  = "{VBD} Verb, past tense"
  show VBG  = "{VBG} Verb, gerund or present participle"
  show VBN  = "{VBN} Verb, past participle"
  show VBP  = "{VBP} Verb, non-3rd person singular present"
  show VBZ  = "{VBZ} Verb, 3rd person singular present"
  show WDT  = "{WDT} Wh-determiner"
  show WP   = "{WP} Wh-pronoun"
  show WPs  = "{WP$} Possessive wh-pronoun"
  show WRB  = "{WRB} Wh-adverb "
  show P    = "{P} Punctuation"
